#!/bin/bash


DEBUG=false
if [[ $1 == "-g" ]];
then
  DEBUG=true
  INPUT=$2
  OUTPUT=$3
else
  INPUT=$1
  OUTPUT=$2
fi

if ! [ -f "$INPUT" ];
then
	echo "Arquivo Inexistente"
	exit 1
fi

if [[ $INPUT == *.c ]];
then
	echo "Compilando arquivo .c"	
	file=$(<$INPUT)

  if ! [[ $file == *"#include"*"<allegro"* ]]; then
    if [ "$DEBUG" = true ]; then
	    if ! [ $OUTPUT ]; then
		    gcc $INPUT -g -o  $HOME/HD/PRGS/.bin/a.out 
	    else
		    gcc $INPUT -g -o  $HOME/HD/PRGS/.bin/$OUTPUT
      fi
    else
      if ! [ $OUTPUT ]; then
	      gcc $INPUT -g -o $HOME/HD/PRGS/.bin/a.out 
      else
        gcc $INPUT -g -o $HOME/HD/PRGS/.bin/$OUTPUT
      fi
    fi
  else
   var="$(cat $INPUT | grep "#include" | grep "allegro_")" #Acha as bibliotecas Allegro (linha)
   libs='allegro-5 ' # Inicializa variável libs

    for len in $var; do # para cada palavra na linha
      gate=false
    
      if [[ $len == "<"* ]]; then # se começar com <
		    for (( i=0; i<${#len}; i++ )); do # para cada letra
			    if [ ${len:$i:1} == '/' ] || [ "$gate" = true ]; then 
			  	# se a letra for '/' ou se já estiver contando
			  	  if [ ${len:$i:1} == '.' ]; then # condição de parada
				  		libs+="-5 " # coloca o -5 para o pkg config achar
				  		break # e termina a contagem da palavra.
				  	fi # termina condição de parada
				  	if [ "$gate" = true ]; then # se estiver contando
				  		libs+=${len:$i:1} # adiciona a letra normalmente em libs
				  	fi #termina if sobre "se *já estava* contando"
				  	gate=true  #começa a contar pq achou '\'
				  fi 
			  done 
		  fi 
	  done   
	  echo Bibliotecas ALLEGRO Adicionais: $libs
    if [ "$DEBUG" = true ]; then
	    if ! [ $OUTPUT ]; then
 		  	gcc $INPUT -g -o $HOME/HD/PRGS/.bin/a.out $(pkg-config --libs $libs) -Wall
  	  else
  	  	gcc $INPUT -g -o $HOME/HD/PRGS/.bin/$OUTPUT $(pkg-config --libs $libs) -Wall
  	  fi
      else
	    if ! [ $OUTPUT ]; then
			  gcc $INPUT -o $HOME/HD/PRGS/.bin/a.out $(pkg-config --libs $libs) -Wall
	 	  else
	 		  gcc $INPUT -o $HOME/HD/PRGS/.bin/$OUTPUT $(pkg-config --libs $libs) -Wall
	 	  fi
    fi
  fi
elif [[ $INPUT == *.rs ]]
then
	echo "Compilando arquivo .rs"	
	if ! [ $OUTPUT ]; then
		rustc $INPUT -o $HOME/HD/PRGS/.bin/a.out 
	else
		rustc $INPUT -o $HOME/HD/PRGS/.bin/$OUTPUT
	fi
fi

